package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/56)
=> CI: bumps version to 0.23.17 [skip ci]

package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/60)
=> Search bar updates

components/AlgoliaSearch/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/61)
=> new updates

Dockerfile, scripts/build-algolia-search.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/62)
=> new update

.github/workflows/build-and-deploy.yml, Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/67)
=> latest changes

.github/workflows/build-and-deploy.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/68)
=> new changes

components/Navbar/index.tsx, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/54)
=> feat: Cookbook Onboard integration

components/Navbar/index.tsx, package.json, yarn.lock
Reverts CoreumFoundation/docs-next#54
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/69)
=> Revert "feat: Cookbook Onboard integration"

.github/workflows/build-and-deploy.yml, Dockerfile, components/AlgoliaSearch/index.tsx, components/Navbar/index.tsx, next.config.mjs, package-lock.json, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/70)
=> feat: update mobile optimization

app/docs/become-validator/page.tsx, app/docs/become-validator/upgrades/page.tsx, app/docs/help/page.tsx, app/docs/modules/page.tsx, app/docs/overview/page.tsx, app/docs/page.tsx, app/docs/tutorials/page.tsx, app/docs/tutorials/use-tokens/page.tsx, app/docs/xrpl-bridge/page.tsx, components/AlgoliaSearch/index.tsx, components/HighlightedText/index.tsx, components/HitComponent/index.tsx, components/Navbar/index.tsx, components/SearchResultsSection/index.tsx, components/Subsection/index.tsx, package.json, utils/types.ts, utils/utils.ts, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/75)
=> fix: build issue and add component-based search functionality

app/docs/tools/page.tsx, components/AlgoliaSearch/index.tsx, components/HighlightedText/index.tsx, components/SearchResultsSection/index.tsx, components/Subsection/index.tsx
improvements
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/76)
=> feat: Mobile optimization, log cleanup, and render performance improve

components/Faucets/index.tsx, components/Navbar/index.tsx, package-lock.json, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/79)
=> refactor: replaced docsbot with @cookbookdev/coreum/react

askcookbook.d.ts, components/Navbar/index.tsx, package.json, yarn.lock
revert of https://github.com/CoreumFoundation/docs-next/commit/e51ee9dfb59bc6178f62feef2b9941cbe1ef431b changes that removed `@cookbookdev/coreum`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/80)
=> revert of commit e51ee9d changes that removed @cookbookdev/coreum package

Dockerfile, scripts/build-algolia-search.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/82)
=> Fix algolia docs upload

app/docs/tools/faucet/faucet.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/83)
=> Fix faucet search result bug

app/docs/become-validator/essentials/system-requirements/system-requirements.mdx, app/docs/become-validator/upgrades/history/history.mdx, app/docs/become-validator/upgrades/main-info/main-info.mdx, app/docs/tutorials/get-started/cli/ledger-nano/ledger-nano.mdx, app/globals.css, next.config.mjs, package-lock.json, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/85)
=> Fix tags rendering in docs

app/docs/modules/coreum-fungible-token/coreum-fungible-token.mdx, app/docs/overview/smart-tokens/smart-tokens.mdx, app/docs/tutorials/build-apps/amm/amm.mdx, app/docs/tutorials/get-started/wasm/deploy-wasm-contract/deploy-wasm-contract.mdx, app/docs/tutorials/get-started/wasm/smart-ft-with-wasm/smart-ft-with-wasm.mdx, app/docs/tutorials/ibc/ibc-smart-contract-call/ibc-smart-contract-call.mdx, app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx, app/docs/tutorials/use-tokens/create-and-manage-ft-with-cli/create-and-manage-ft-with-cli.mdx, app/docs/tutorials/use-tokens/smart-ft-with-wasm/smart-ft-with-wasm.mdx, components/Sidebar/constants.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/86)
=> Update extension tutorial with the DEX support.

scripts/build-algolia-search.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/89)
=> Fix: algolia search indexing script

mdx-components.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/90)
=> Fix: Scroll margin on anchor items

app/docs/modules/coreum-dex/coreum-dex.mdx, app/docs/modules/coreum-dex/page.tsx, app/docs/modules/cosmos-non-fungible-token/page.tsx, app/docs/overview/modules/page.tsx, app/docs/tutorials/get-started/cli/coreum-dex-cli/coreum-dex-cli.mdx, app/docs/tutorials/get-started/cli/coreum-dex-cli/page.tsx, app/docs/tutorials/get-started/cli/ledger-nano/page.tsx, app/docs/tutorials/get-started/golang/create-ft/page.tsx, app/docs/tutorials/get-started/typescript/coreum-js/page.tsx, app/docs/tutorials/integrate-coreum/wallet-integration/page.tsx, components/Sidebar/constants.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/88)
=> Add DEX module docs and CLI tutorial.

app/globals.css, mdx-components.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/91)
=> Fix: title is covered by navbar when clicking on search

app/docs/become-validator/essentials/system-requirements/system-requirements.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/95)
=> Fix: Update validator minimum requirements

app/docs/become-validator/upgrades/main-info/main-info.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/96)
=> Add upgrade instructions for v4.1.2 mainnnet upgrade

app/docs/tutorials/xrpl-bridge-integration/page.tsx, app/docs/tutorials/xrpl-bridge-integration/xrpl-bridge-integration.mdx, components/Sidebar/constants.ts, package-lock.json, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/100)
=> feat: add docs for coreum to xrpl bridge transactions

app/docs/become-validator/essentials/how-much-fund-to-create-validator/how-much-fund-to-create-validator.mdx, app/docs/tutorials/integrate-coreum/cex-integrations/cex-integrations.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/101)
=> Update validator active set number to 64

app/docs/become-validator/validator/run-validator/run-validator.mdx, components/Footer/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/103)
=> Fix discord link

app/docs/tutorials/get-started/setup-cli/setup-cli.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/102)
=> Add other rpc providers

app/docs/become-validator/run-full-node/run-full-node.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/105)
=> Fix state sync trusted blocks instructions script

app/docs/xrpl-bridge/run-relayer/run-relayer.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/104)
=> Add XRPL bridge section on metrics

app/docs/api/protobuf-v5/page.tsx, app/docs/api/protobuf-v5/protobuf-v5.mdx, app/docs/core_dex/api-server/overview/overview.mdx, app/docs/core_dex/api-server/update-service/update-service.mdx, app/docs/core_dex/overview/overview.mdx, components/Navbar/index.tsx, components/Sidebar/constants.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/107)
=> Add protobuf v5

app/docs/xrpl-bridge/register-new-token/register-new-token.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/108)
=> Add additional explanation on how to add token to the bridge

app/docs/become-validator/essentials/network-variables/network-variables.mdx, app/docs/tutorials/get-started/setup-cli/setup-cli.mdx, app/docs/xrpl-bridge/install-relayer/install-relayer.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/111)
=> Add RPC node warning to the doc

.github/workflows/build-and-deploy.yml, .typos.yaml, app/docs/next/become-validator/troubleshooting/troubleshooting.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/112)
=> Add validator troubleshooting guide

app/docs/next/modules/coreum-dex/coreum-dex.mdx, app/docs/v4/modules/coreum-dex/coreum-dex.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/114)
=> Remove disclaimer of DEX being deployed only on devnet

app/docs/next/modules/coreum-deterministic-gas/coreum-deterministic-gas.mdx, app/docs/next/modules/coreum-dex/coreum-dex.mdx, app/docs/next/modules/coreum-fee-model/coreum-fee-model.mdx, app/docs/next/modules/coreum-fungible-token/coreum-fungible-token.mdx, app/docs/next/modules/coreum-non-fungible-token/coreum-non-fungible-token.mdx
This pull request updates the documentation for several Coreum modules, adding details about new features, parameters, and proto definitions. The most important changes include updates to deterministic gas calculations, enhancements to the DEX module, and new sections for proto definitions across multiple modules.
* Added a formula for calculating gas for the `/coreum.asset.ft.v1.MsgUpdateDEXWhitelistedDenoms` message, including details about `DEXUpdateWhitelistedDenomBaseGas` and `DEXWhitelistedPerDenomGas`.
* Updated the `order_id` attribute to include a regular expression for validation.
* Clarified that the `max_orders_per_denom` parameter can be changed via governance proposals, with a link to check the current value.
* Added a new section describing the "Order Sequence" feature, …
=> Reflect the recent changes in the Coreum code base (April 2025)

app/docs/next/nodes-and-validators/upgrades/upgrades-instructions/main-info.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/116)
=> Add mainnet v5 upgrade instructions

app/docs/next/nodes-and-validators/upgrades/upgrades-history/history.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/118)
=> Add v5 mainnet upgrade to upgrade history

app/docs/next/tutorials/get-started/golang/transfer-funds/transfer-funds.mdx, app/docs/next/tutorials/integrate-coreum/cex-integrations/cex-integrations.mdx, app/docs/v4/tutorials/get-started/golang/transfer-funds/transfer-funds.mdx, app/docs/v4/tutorials/integrate-coreum/cex-integrations/cex-integrations.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/117)
=> Fix GRPC codec

app/docs/next/layout.tsx, app/docs/v4/layout.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/120)
=> Remove mainet deployment warning block

app/docs/next/help/how-to-unjail-my-validator/page.tsx, app/docs/next/nodes-and-validators/run-sentry-node/page.tsx, app/docs/next/nodes-and-validators/upgrades/upgrades-history/page.tsx, app/docs/next/nodes-and-validators/upgrades/upgrades-instructions/page.tsx, app/docs/next/tutorials/build-apps/development-environment/page.tsx, app/docs/next/tutorials/get-started/cli/transfer-funds-with-cli/page.tsx, app/docs/next/tutorials/smart-tokens/create-and-manage-nft/page.tsx, app/docs/next/tutorials/smart-tokens/use-cases/airdrop-token/page.tsx, app/docs/v4/help/how-to-unjail-my-validator/page.tsx, app/docs/v4/nodes-and-validators/run-sentry-node/page.tsx, app/docs/v4/nodes-and-validators/upgrades/upgrades-history/page.tsx, app/docs/v4/nodes-and-validators/upgrades/upgrades-instructions/page.tsx, app/docs/v4/tutorials/build-apps/development-environment/page.tsx, app/docs/v4/tutorials/get-started/cli/transfer-funds-with-cli/page.tsx, app/docs/v4/tutorials/smart-tokens/create-and-manage-nft/page.tsx, app/docs/v4/tutorials/smart-tokens/use-cases/airdrop-token/page.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/122)
=> Fix docs pages build

.github/workflows/docs-rebuild.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/125)
=> Add docs rebuild trigger to docs repo

components/FAQList/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/docs-next/128)
=> Replace quotes with apostroph in FAQ page
